### ISSUE TITLE
[http/https] shallow clone assumes options is a pojo, but it could be a URL.

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#111]
Need to test to see how much this will break things.

**Comment by markgaylard** [comment]
The [got](https://www.npmjs.com/package/got) library uses the URL class and as a result the beeline instrumentation doesn't work - it breaks things because the `combinedOptions` object created [here](https://github.com/honeycombio/beeline-nodejs/blob/main/lib/instrumentation/https.js#L47) is empty

**Comment by vreynolds** [comment]
Should be fixed by #361
