### ISSUE TITLE
Problematic typo in the website docs for customizing instrumented packages

### ISSUE THREAD

**Issue by jceipek** [honeycombio/beeline-nodejs#119]
In _each of the three sections_ in https://docs.honeycomb.io/beeline/nodejs/#customizing-instrumented-packages, `enabledInstrumentations` is mistakenly written as `enabledInstrumentation`: 

```
require("honeycomb-beeline")({
  enabledInstrumentation: ["http", "https"],
  /* ... additional configuration ... */
});
```

should read

```
require("honeycomb-beeline")({
  enabledInstrumentations: ["http", "https"],
  /* ... additional configuration ... */
});
```

Unfortunately, the configure opts aren't checked against a schema and therefore using `enabledInstrumentation` as documented results in a silent failure.

https://github.com/honeycombio/beeline-nodejs/blob/master/lib/instrumentation.js#L150

I'd happily open a pull request for `docs.honeycomb.io` but I can't find the relevant repo if it happens to be public.

**Comment by toshok** [comment]
Unfortunately the repo isn't public :(  I did fix the docs bugs just a few minutes ago, though - thanks!
