### ISSUE TITLE
enable going off-road in the onramp

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#12]
This onramp is meant to be an easy way to get people started sending events with useful (but generic) data about the node modules they're using.  This obviously only gets people so far.

We need to make it super easy to add additional context to events.  Individual metrics are somewhat nicely served by the `magic.customContext.add(key, value)` api.  But that is only nice for single point in time metrics.  Timers around functions, or worse - async operations, are much more difficult and gross to add.

@nathanleclaire mentions some NR sugar here: https://github.com/honeycombio/honeycomb-nodejs-magic/pull/4#issuecomment-362720033

adding something along those lines would help in the case where a user isn't using a supported top-level module.  Right now the only top-level module is express.  People using less popular frameworks (or heck, the framework they wrote on their own) should be able to get reasonable instrumentation out of it just as easily.

**Comment by BrianChristie** [comment]
Just wondering if there's been any further thoughts on adding NR style timer sugar as referenced above and [honeycombio#4 (comment)](https://github.com/honeycombio/beeline-nodejs/pull/4#issuecomment-362720033)?

**Comment by toshok** [comment]
Hey @BrianChristie, just put up #66 which hopefully can/will address everything.  Comments/questions absolutely welcome over there.  Not expecting to land it until after middle of next week at the earliest.
