### ISSUE TITLE
Add support for the `dataset` field in the trace propagation header

### ISSUE THREAD

**Issue by maplebed** [honeycombio/beeline-nodejs#135]
The Go beeline supports adding a `dataset` field to the trace propagation header (`x-honeycomb-trace`). The effect of including this field is that spans from the downstream service should be sent to the indicated dataset. The rest of the beelines should implement this addition.

**Comment by toshok** [comment]
This is in as of aea960203cc72255125fa3c9f045ae2ca0811b65
