### ISSUE TITLE
instrumentation does not work if modules are compiled into same file

### ISSUE THREAD

**Issue by mjm** [honeycombio/beeline-nodejs#139]
I'm writing serverless functions in TypeScript that run in Zeit Now, and I want to use this Beeline to track them. They use express, but the express instrumentation never kicks in.

I did some digging and the reason is that the beeline hooks into Node's Module API and wraps the loading of modules. But Zeit Now uses their ncc compiler, which uses webpack to compile all the JavaScript into one file. In this situation, express is inlined into the file, and Node's `require` is never called for express, so it never gets instrumented.

I'm not sure how possible it is to detect this scenario and hook into webpack's require mechanism, but it would be nice if that could be done.

**Comment by toshok** [comment]
bundler discussion moved over to #172
