### ISSUE TITLE
Fastify documentation

### ISSUE THREAD

**Issue by nathanleclaire** [honeycombio/beeline-nodejs#145]
A customer requested support for https://www.fastify.io/

**Comment by camerondunn-ns8** [comment]
It looks like Fastify support was added in [this commit](https://github.com/honeycombio/beeline-nodejs/commit/d70c36aa59336d094dd4351a1da3bcb81ee99cf3), but it's not mentioned in any docs or anywhere that I can find.

Is anymore action being taken for Fastify? Should we be Ok to use that fastify support?

**Comment by toshok** [comment]
should be okay - will address docs shortcomings before closing this issue, though (and change the title).
