### ISSUE TITLE
Documentation for beeline.addContext is wrong

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-nodejs#149]
https://docs.honeycomb.io/getting-data-in/javascript/beeline-nodejs/

> Note that beeline.addContext only adds fields to the current span. In order to add fields to all downstream spans, use beeline.customContext.add instead:

![](https://cl.ly/406fb063de49/Image%202019-07-19%20at%2010.53.32%20am.png)

From reading the code and experimenting with the SDK it seems that `beeline.addContext()` actually adds the context to every active/subsequent span in the trace. This is fine, and useful, but it seems there's no way to add context to the currently active span without keeping a reference to it that you pass around and manually add entries to?

It seems this behaviour was changed in: https://github.com/honeycombio/beeline-nodejs/pull/54

https://honeycombpollinators.slack.com/archives/C4T3A32CX/p1563529998355500

**Comment by jugglingthebits** [comment]
I am seeing the same thing, but it seems like a bug to me - after all, why should `addContext(..)` propagate to all subsequent spans when `addCustomContext(..)` does exactly that?

![grafik](https://user-images.githubusercontent.com/3235163/61936366-dd9f5600-af8c-11e9-854e-dee1589ae86f.png)

**Comment by toshok** [comment]
yep, this is totally a bug.  should be fixed by #184
