### ISSUE TITLE
`https` instrumentation should be removed as it is covered by `http` instrumentation

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-nodejs#150]
I'm not well-versed in how nodejs works, but it sounds like nodejs delegates all calls to `https` to the `http` package. This results in 2 spans being recorded for every `https` request, which is quite confusing.  This appears to be acknowledged in the code:

https://github.com/honeycombio/beeline-nodejs/blob/c55f99ff8dbe99bcd45cea19b123b33a3490a757/lib/instrumentation/https.js#L52-L57

Is the https instrumentation still necessary if the `http` instrumentation will always be invoked on every request? I've worked around the double instrumentation by disabling `https` instrumentation, but I'm wondering if a better first-run experience for all users would be to remove `https` instrumentation, or at least disable it on the affected versions of node.

**Comment by BRMatt** [comment]
Any thoughts on this? It's incredibly frustrating that out of the box the beeline creates spans like this (note that each pair of nested spans represents a single request):

![](https://cl.ly/a8ac72166333/Image%202020-01-08%20at%205.17.12%20pm.png)

**Comment by toshok** [comment]
are you on node v8?  That's been removed from the officially supported versions of node (it dropped off LTS).

**Comment by BRMatt** [comment]
I believe we were on v8 at the time, yes. We're now on the LTS and I think I had to enable both instrumentations when we upgraded.
