### ISSUE TITLE
Beeline crashes with type error if startSpan/startAsyncSpan is called outside of a trace

### ISSUE THREAD

**Issue by BRMatt** [honeycombio/beeline-nodejs#179]
We have an app that has 3 separate entry points (3 consumers of 3 different queues). While adding some instrumentation to one of the entry points I realised the other 2 consumers were completely broken.

It seems that `startSpan` and `startAsyncSpan` assume the async tracker will _always_ return an object containing a stack. If this isn't the case, the beeline crashes. These are the lines where the error is being raised:

https://github.com/honeycombio/beeline-nodejs/blob/ab0c5393b995d2778f73da8440f0128784e23a9d/lib/api/libhoney.js#L110-L111

https://github.com/honeycombio/beeline-nodejs/blob/ab0c5393b995d2778f73da8440f0128784e23a9d/lib/api/libhoney.js#L137-L138

The error being raised on line 138 is:

```
TypeError: Cannot read property 'stack' of undefined at LibhoneyEventAPI.startAsyncSpan
```

We can see that `getTracked()` is `get()`ing an item from a `Map`, but `get()` [returns undefined if the value does not exist](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get):

https://github.com/honeycombio/beeline-nodejs/blob/ab0c5393b995d2778f73da8440f0128784e23a9d/lib/async_tracker.js#L16-L18

Ideally the beeline should be invisible and not crash if it's running outside the context of a trace.

**Comment by BRMatt** [comment]
I fixed this in our fork of the package by copying the checks from the other helpers:

https://github.com/geckoboard/beeline-nodejs/commit/b4379d0f3ce31dbe4566e3ae629505579d71d872

**Comment by toshok** [comment]
going back through bugs, and \o/ - will fold these in.
