### ISSUE TITLE
X-Amzn-Trace-Id header being parsed incorrectly

### ISSUE THREAD

**Issue by paulosman** [honeycombio/beeline-nodejs#192]
From [the elastic load balancing docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html) : 

The `X-Amzn-Trace-Id` header contains fields with the following format: 

`Field=version-time-id`

We currently parse `version-time-id` as a single identifier. The [honeyalb](https://github.com/honeycombio/honeyaws) cmd parses the fields according to the documentation above. When setting `trace.trace_id` and `trace.parent_id` from the incoming header, we should do the same in all of the beelines.

**Comment by paulosman** [comment]
Here's the parsing code in the honeyaws package:

https://github.com/honeycombio/honeyaws/blob/master/publisher/publisher.go#L157

**Comment by toshok** [comment]
hm, the amazon sdks do it the same way (version-time-id = the id)..

**Comment by paulosman** [comment]
@toshok yeah - it might not be important that we isolate the identifier, just that we do it the same way between beelines and other integrations.

**Comment by toshok** [comment]
aws-xray-sdk-node that is.

parsing: https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/utils.js#L176

used here in the express middleware: https://github.com/aws/aws-xray-sdk-node/blob/695f0498d3455a98c393d3720ee213384527f115/packages/restify/lib/restify_mw.js#L45

**Comment by paulosman** [comment]
Going to fix this in honeyaws
