### ISSUE TITLE
[express/graphql]: we lost our tracking somewhere in the stack handling this request

### ISSUE THREAD

**Issue by bautistaaa** [honeycombio/beeline-nodejs#195]
**POST requests via `RESTDataSource` from `apollo-datasource-rest` are not being captured. GET requests seem to be fine.**

`honeycomb-beeline:express -------------------
  honeycomb-beeline:express     honeycomb-beeline error: we lost our tracking somewhere in the stack handling this request
  honeycomb-beeline:express     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:express     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
  honeycomb-beeline:express     out any application stack frames if you'd rather not share those
  honeycomb-beeline:express     Error
  honeycomb-beeline:express     at LibhoneyEventAPI.askForIssue (/node_modules/honeycomb-beeline/lib/api/libhoney.js:295:7)
  honeycomb-beeline:express     at Object._askForIssue (/node_modules/honeycomb-beeline/lib/api/index.js:137:20)
  honeycomb-beeline:express     at api.bindFunctionToTrace (/node_modules/honeycomb-beeline/lib/instrumentation/express.js:129:11)
  honeycomb-beeline:express     at /node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
  honeycomb-beeline:express     at ServerResponse.<anonymous> (/node_modules/honeycomb-beeline/lib/instrumentation/express.js:158:12)
  honeycomb-beeline:express     at ServerResponse.writeHead (/node_modules/on-headers/index.js:35:16)
  honeycomb-beeline:express     at ServerResponse.writeHead (/node_modules/on-headers/index.js:44:26)
  honeycomb-beeline:express     at ServerResponse._implicitHeader (_http_server.js:200:8)
  honeycomb-beeline:express     at ServerResponse.end (/node_modules/compression/index.js:103:14)
  honeycomb-beeline:express     at ServerResponse.send (/node_modules/express/lib/response.js:221:10)
  honeycomb-beeline:express     at apollo_server_core_1.runHttpQuery.then (/node_modules/apollo-server-express/src/expressApollo.ts:49:15)
  honeycomb-beeline:express     at /node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
  honeycomb-beeline:express     at process._tickCallback (internal/process/next_tick.js:68:7)
  honeycomb-beeline:express     current request context:
  honeycomb-beeline:express 0: {"meta.type":"express","meta.package_version":"4.16.4","name":"request","request.host":"localhost","request.original_url":"/graphql","request.remote_addr":"::1","request.secure":false,"request.method":"POST","request.scheme":"http","request.path":"/graphql","request.query":{},"request.http_version":"HTTP/1.1","request.fresh":false,"request.xhr":false,"trace.trace_id":"8c5506e7-d6d2-44fa-b443-a00c0fdae744","trace.span_id":"08bd4350-51b6-4a93-a906-bae26809859b","startTime":1585871367510,"startTimeHR":[1497326,294864427]}
  honeycomb-beeline:express     ------------------- +43s`

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
