### ISSUE TITLE
startAsyncSpan fails to capture parent span

### ISSUE THREAD

**Issue by jugglingthebits** [honeycombio/beeline-nodejs#196]
After updating `beeline-nodejs` to 2.1.0, we started getting broken traces in HC. All spans are missing a parent span.

![grafik](https://user-images.githubusercontent.com/3235163/79494214-eb1cd480-8022-11ea-851a-378e846c9cd3.png)

When debugging `startAsyncSpan`, I notice that `parentId` is undefined. Line https://github.com/honeycombio/beeline-nodejs/blob/efc06456001a3f972ef86b6da8ba81ee8e33481a/lib/api/libhoney.js#L151 is trying to fetch `parentId` from the last stack item, but this item is of type `Span` and contains the required property `trace.span_id` inside a property `payload`: https://github.com/honeycombio/beeline-nodejs/blob/efc06456001a3f972ef86b6da8ba81ee8e33481a/lib/api/span.js#L7 . So it can't find it, which leaves all spans started using `startAsyncSpan` without a parent span.

IMO this break all instances of `startAsyncSpan`, because they all fail to capture the parent span.

**Comment by toshok** [comment]
ohh, nice find.  is this because you have async spans as children of synchronous spans (or rather, some number of synchronous between async spans)?

**Comment by toshok** [comment]
regardless, checking out the PR :)

**Comment by toshok** [comment]
oh derp, I see - right.  we're missing the `.payload` in the async span case 👍

**Comment by jugglingthebits** [comment]
What's your timeline to release this? ATM the last released package is not usable (I assume for most people using any of the integrations).

**Comment by toshok** [comment]
eta like 10 minutes I think
