### ISSUE TITLE
No instrumentation on `await`ed Mongoose queries

### ISSUE THREAD

**Issue by josh-byster** [honeycombio/beeline-nodejs#199]
I wanted to first say thank you very much for such a wonderful, easy-to-use library! I've very much enjoyed using the platform. I noticed the patched Mongoose calls won't get instrumented if there's an `await` call with no `.then` chained.

For example, when I run in debug mode and perform a query like the following:
```
let testResult = await Model.find({ name: "test" }).lean();
```
I see nothing with `name: "test"` logged out to the console, nor is it showing in the corresponding trace on the website.

However, if I were to instead chain off, say, an identity function off the promise:
```
let testResult = await Model.find({ name: "test" }).lean().then(arg => arg);
```

It works as I would expect. I figured this may have to do with #76 and how functions are patched in instrumentation.

Another question I had that is related: if I wrap an instrumented query in a custom span, for example:

```
const span = beeline.startSpan({ name: "Deserialize User Query" });
User.findById(id, function (err, user) {
    beeline.finishSpan(span);
    done(null, user);
})
```   

Despite this only wrapping that one query and nothing else, I see consistently the Mongo queries taking up only a fraction of the entire span. Is there any reason why that might be? Is it just boiling down to process scheduling or is only a piece of the query instrumented? I would think up the `findOne` would take up the entire time. This seems to happen with longer queries as well, still only taking up a fraction of the span that wraps it.
![image](https://user-images.githubusercontent.com/8664074/80858791-4b199a80-8c21-11ea-8bea-b09720f38be2.png)

Thank you so much!

**Comment by twpol** [comment]
I've just been debugging the first issue, and found that `await model.find(...)` doesn't capture the query but `await model.find(...).exec()` does.

I don't entirely understand the problem, and it might be a Node issue (I'm on 12.18.3), but awaiting the query without exec ends up in the `Query.prototype.then` method of Mongoose but there is no async tracking from Node (it's all zero).

I managed to fix this with the following Mongoose shim in the Beeline:

```javascript
  shimmer.wrap(mongoose.Query.prototype, "setOptions", function(original) {
    return function(options, overwrite) {
      this.then = api.bindFunctionToTrace(this.then);
      return original.apply(this, [options, overwrite]);
    };
  });
```

What this does is take advantage of the fact most (all?) query methods will call `this.setOptions` and we can then bind the `then` method explicitly to the current trace context.

**Comment by djanowski** [comment]
[This PR](https://github.com/honeycombio/beeline-nodejs/pull/393) adds a basic (failing) test for this issue, and [this PR](https://github.com/honeycombio/beeline-nodejs/pull/394) fixes it.

@vreynolds WDYT?

**Comment by bdarfler** [comment]
Oops, closed by mistake.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
