### ISSUE TITLE
Allow sending event data asynchronously to api.honeycomb.com, add support to configure generating events to STDOUT

### ISSUE THREAD

**Issue by robwdux** [honeycombio/beeline-nodejs#221]
We are using AWS Lambda and AWS Cloudwatch would like the ability same as what is provided in the [Golang Beeline](https://docs.honeycomb.io/getting-data-in/go/beeline-tutorial/#generate-events-to-stdout).

performance - allow trading user facing latency with http synchronous calls for a slight delay in event data arriving at Honeycomb in addition to Cloudwatch costs

durability - allows buffering data with Cloudwatch/Kinesis if necessary at times (don't drop any event data on the floor)

reliability/determinism - had issues with Lambda / Node  non-async handler / callback with event loop due to having to have `startTrace` outside async functions.

Also noted [here](https://docs.honeycomb.io/learning-about-observability/about-instrumentation/serverless/)
> In the Honeycomb Serverless stack, we emit structured events to logfiles, and then use lambda functions that upload these logs to Honeycomb

**Comment by toshok** [comment]
so there is a way to get event traffic to stdout:

```
require("honeycomb-beeline")({
  transmission: "writer"
});
```

but there's a libhoney issue with quoting the output, fixed in https://github.com/honeycombio/libhoney-js/pull/73.  we'll need to land that fix + bump the `libhoney` dep here.

**Comment by toshok** [comment]
The fix for quoting required adding a new transmission type, so the above snippet will become this, once the beeline's dep on libhoney is bumped post libhoney release:

```
require("honeycomb-beeline")({
  transmission: "console"
});
```

**Comment by robwdux** [comment]
thanks again @toshok for this. When transmission is set to console, may the writekey not be required?  `.writeKey must be a non-empty string`
