### ISSUE TITLE
Propagated trace context is double-prefixed to `app.app.`

### ISSUE THREAD

**Issue by twpol** [honeycombio/beeline-nodejs#229]
When you do `beeline.addTraceContext({ foo: 42 })` it adds `app.foo = 42` to every span in-process, as expected.

However, when that process calls out to another, the source service sends the trace context here:

https://github.com/honeycombio/beeline-nodejs/blob/97e9c6af3c61c965ba055a844330d96045128f02/lib/instrumentation/http.js#L74

Which puts a serialised form of `app.foo = 42` into the propagation header. Then the target service receives the trace context here:

https://github.com/honeycombio/beeline-nodejs/blob/97e9c6af3c61c965ba055a844330d96045128f02/lib/instrumentation/express.js#L124

Unfortunately, that's another call to `addTraceContext` so this process adds `app.app.foo = 42` to every span.

It is probably not intentional that the `app.` prefix is duplicated.

**Comment by katiebayes** [comment]
Thanks for the issue! We have an open PR that should resolve this behavior; propagated fields will no longer get prefixed and will propagate unaltered. We'll be releasing this asap. If you want to take a look: https://github.com/honeycombio/beeline-nodejs/pull/226

**Comment by katiebayes** [comment]
This fix has landed and shipped! Updating to v2.2.0 should take care of this. Other release notes here: https://github.com/honeycombio/beeline-nodejs/releases/tag/v2.2.0
