### ISSUE TITLE
Allow disabling capturing client IP addresses for anonymization

### ISSUE THREAD

**Issue by jugglingthebits** [honeycombio/beeline-nodejs#235]
The beeline currently captures client IP addresses from requests and transmits them as part of trace payload. IP addresses are considered Personally Identifiable Information (PII) in some countries in the E.U. (whether it's all countries in the E.U. - I don't know).

As the Privacy Shield agreement between the U.S. and the E.U. has been declared invalid, this means transmitting client IP addresses to Honeycomb is not compliant with current regulation.

It would be useful to introduce a config parameter for disabling transmitting client IP addresses, effectively anonymizing traces. 

Then privacy laws wouldn't apply to using Honeycomb any more, because they only apply to PII.

**Comment by jugglingthebits** [comment]
I'd also be interested if you'd take a PR for this one.

**Comment by eanakashima** [comment]
@jugglingthebits thanks for the report and sorry for the delay here. For now, I believe your best option is to delete the fields you know contain PII with a [presend hook](https://github.com/honeycombio/beeline-nodejs/pull/125). We still need to update our node docs with some more robust examples of how this could work, but our Ruby docs have an [example](https://docs.honeycomb.io/getting-data-in/ruby/beeline/#rails) you can get the gist from.

We're happy to consider allowing configuration around capturing IP addresses in the future, although we worry about framing this as a toggle for turning off capture of _all_ PII collected by default — depending on the app, there may be other fields like the request url that include PII as well.

**Comment by jugglingthebits** [comment]
Thanks for the hint towards presend hooks. I think I can work with that.

I'd agree the config name shouldn't indicate that this would be about not capturing PII. Instead, name it so that it refers to IP addresses only (i.e. `capture_ip` or so). Just my 2cts.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
