### ISSUE TITLE
Non-Express support

### ISSUE THREAD

**Issue by RyKilleen** [honeycombio/beeline-nodejs#255]
It's my understanding that to use Beeline NodeJS, I must be using Express.

Support for non-Express NodeJS out of the box would be ideal if it's feasible. My use-case includes Netlify functions that are plain Node.

I'm currently piloting Honeycomb and this was an interesting pain point to run into, considering it's named Beeline NodeJS. I've switched to the Javascript SDK for now.

**Comment by toshok** [comment]
This is unfortunate and we should correct this page in the docs:

![image](https://user-images.githubusercontent.com/24245/95354811-b8d58c80-0879-11eb-9f23-52a5847a1201.png)

Express use isn't required, and hasn't been for quite some time.  express (and fastify) support only exists to provide a middleware that starts traces for you.

The [beeline api](https://github.com/honeycombio/beeline-nodejs/blob/main/docs/API.md) is always available (indeed express and fastify middlewares use it), and you can start traces using it anywhere in any node program.  It occurs to me that disclaimer at the top should _also_ be corrected.  The API documented at that URL is for anyone writing either custom auto-instrumentation support (like the express or fastify support), as well as adding instrumentation outside of auto-instrumentation, which is your use-case here.

**Comment by RyKilleen** [comment]
I see! It's likely the vague error I was running into is unrelated then, I'll give it another go. Thank you for the info!

**Comment by toshok** [comment]
also thanks for creating this issue.  landed a PR for our docs site to clear up the requirement text there, as well as #256 in this repo.  🎉 

let us know how it goes!
