### ISSUE TITLE
X-Honeycomb-Trace header name is case-sensitive, non-compliant w/ RFC 2616 Section 4.2

### ISSUE THREAD

**Issue by omriharel** [honeycombio/beeline-nodejs#267]
[Section 4.2](https://tools.ietf.org/html/rfc2616#section-4.2) of RFC 2616 states that "Field names are case-insensitive".

Honeycomb's client libs are typically the entity which injects _and_ parses the special `X-Honeycomb-Trace` header, so relying on that specific casing isn't usually a problem.

However, when the parsing logic is invoked as part of a wrapper around e.g. a lambda function, if that wrapper performs any pre-processing on header names (i.e. to allow for quick lookups), this will also mean that the Honeycomb client might look for a header whose name has changed and that will, of course, fail.

A possible workaround is to give the header special treatment in the wrapper and leave it as-is, but I think it would be cleaner if Honeycomb's client libs would:

- be resilient to header names with any casing (ideally)
- or check for an all-lowercase or all-uppercase header name in addition to the current title-case name. This is a more performance-friendly approach that still isn't compliant, but would get the trick done for 99% of use cases

Thank you for reading!

**Comment by MikeGoldsmith** [comment]
Hi @omriharel - thanks for raising the issue. We'll get back to you soon on how we might be able to resolve this.

**Comment by vreynolds** [comment]
Hello @omriharel, thanks for your patience. 

We got a chance to investigate, and it looks like the headers are read as all-lowercase both in the [default parser](https://github.com/honeycombio/beeline-nodejs/blob/main/lib/instrumentation/trace-util.js#L10) and the [Honeycomb parser hook](https://github.com/honeycombio/beeline-nodejs/blob/main/lib/propagation/honeycomb.js#L133).

While you're correct in that it's not ideal per-spec, I believe the assumption there was based on Node's handling of request headers ([Node lower-cases all incoming request headers](https://nodejs.org/ja/docs/guides/anatomy-of-an-http-transaction/#method-url-and-headers)).

You mentioned that assuming all-lowercase might suffice for your use case. Is that the case?

**Comment by vreynolds** [comment]
Going to close this for now. Let us know if the current header treatment doesn't work for your use case. ✌️
