### ISSUE TITLE
Add docs for running serverless apps locally

### ISSUE THREAD

**Issue by jonocairns** [honeycombio/beeline-nodejs#269]
Hi there! 

This isn't really an issue, more of an experience running serverless offline with the honeycomb mock implementation. It looks like you use `async_hooks.executionAsyncId()` for spanId / traceIds. In sls offline there is no guarantee that the same process will be running the request when running multiple lambdas, therefore you can get intermittent errors around missing traceIds / spanIds / stacks (as the event can be passed through but when it attempts the ctx map lookup it won't find anything).

To get around this you can add this flag in your sls offline run script in package.json `--useChildProcesses` which will ensure the context. (e.g. `sls offline --host 0.0.0.0 --useChildProcesses --lambdaPort 3004`)

Hopefully this might help someone else in the same situation :)

**Comment by vreynolds** [comment]
Thanks for the information. Hopefully someone else will see this when they need it.
