### ISSUE TITLE
FastifyDeprecation: request.req -> request.raw

### ISSUE THREAD

**Issue by LewisJEllis** [honeycombio/beeline-nodejs#271]
Getting this with Fastify:
```
(node:46560) [FSTDEP001] FastifyDeprecation: You are accessing the Node.js core request object via "request.req", Use "request.raw" instead.
```

Looks like it should just be a small `s/request.req/request.raw/g` tweak here: https://github.com/honeycombio/beeline-nodejs/blob/main/lib/instrumentation/fastify.js#L99-L103

**Comment by vreynolds** [comment]
Fixed in [v2.6.0](https://github.com/honeycombio/beeline-nodejs/releases/tag/v2.6.0)
