### ISSUE TITLE
mongodb transactions are not able to be parsed

### ISSUE THREAD

**Issue by kanolato** [honeycombio/beeline-nodejs#322]
Just recently my team enabled includeDocuments on the mongodb instrumentation:
```
beeline({
  writeKey: process.env.HONEYCOMB_API_KEY || 'abc123',
  dataset: 'XXXX',
  serviceName: 'XXXX,
  samplerHook: require('./src/o11y/samplerHook'),
  disableInstrumentation: !JSON.parse(process.env.O11Y_ENABLED || false),
  mongodb: {
    includeDocuments: true,
  },
});
```

As soon as we saw it live we started to see a big increase in request erroring and also in the spans they have.
Prior ` includeDocuments: true`
![image](https://user-images.githubusercontent.com/8549544/111619577-6d42e980-87ee-11eb-9ca2-2d3bd7ed4631.png)
On ` includeDocuments: true`
![image](https://user-images.githubusercontent.com/8549544/111619524-5d2b0a00-87ee-11eb-881a-9def088cd9b3.png)

The errors was always the same:
```
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'NativeTopology'
| property 's' -> object with constructor 'Object'
| property 'sessionPool' -> object with constructor 'ServerSessionPool'
--- property 'topology' closes the circle
at JSON.stringify (<anonymous>)
at LibhoneyEventAPI.finishSpan (/app/node_modules/honeycomb-beeline/lib/api/libhoney.js:201:34)
at Object.finishSpan (/app/node_modules/honeycomb-beeline/lib/api/index.js:116:20)
at /app/node_modules/honeycomb-beeline/lib/instrumentation/mongodb.js:79:23
at /app/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
TypeError: Converting circular structure to JSON
--> starting at object with constructor 'NativeTopology'
| property 's' -> object with constructor 'Object'
| property 'sessionPool' -> object with constructor 'ServerSessionPool'
--- property 'topology' closes the circle
at JSON.stringify (<anonymous>)
at LibhoneyEventAPI.finishSpan (/app/node_modules/honeycomb-beeline/lib/api/libhoney.js:201:34)
at Object.finishSpan (/app/node_modules/honeycomb-beeline/lib/api/index.js:116:20)
at /app/node_modules/honeycomb-beeline/lib/instrumentation/mongodb.js:79:23
at /app/node_modules/honeycomb-beeline/lib/async_tracker.js:47:19
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Because of the way we have implemented transactions, this was retried again and again with a WrinteConflict error, thousands of times.
![image](https://user-images.githubusercontent.com/8549544/111620472-6ff20e80-87ef-11eb-99d9-a82e62039407.png)

We are right now using:
```
"honeycomb-beeline": "^2.6.0",
"mongodb": "^3.5.7",
```

I'm available for anything else that you might want to know, I will try to investigate what happened too

**Comment by vreynolds** [comment]
Oof, that looks gnarly! Can you share a sample code snippet that makes the mongo query? 

I'm guessing that somehow the document we're trying to serialize has a circular reference (e.g. if it's actually the query object). The beeline certainly shouldn't blow up your stack, even if that's the case.

**Comment by vreynolds** [comment]
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.
