### ISSUE TITLE
Type of `bindFunctionToTrace` is wrong

### ISSUE THREAD

**Issue by gmunguia** [honeycombio/beeline-nodejs#412]
Currently, the type of `bindFunctionToTrace` is `bindFunctionToTrace<F>(fn: SpanFn<F>): F;` (see https://github.com/honeycombio/beeline-nodejs/blob/main/lib/types.d.ts#L143).

However, I think the type should be `bindFunctionToTrace<F>(fn: F): F;`, because `bindFunctionToTrace` doesn't change the type of the function it binds.

**Comment by MikeGoldsmith** [comment]
Hi @gmunguia 

Thanks for raising the issue. The [SpanFn<F>](https://github.com/honeycombio/beeline-nodejs/blob/main/lib/types.d.ts#L92) is just used as a utility alias to capture and expand input args. While it's not strictly necessary, we've used it in a couple of places and don't believe it causes any problems.

I'm going to close this as "won't fix". Please re-open if you feel we should reconsider. Thanks.
