### ISSUE TITLE
Incorrect typescript type for `bindFunctionToTrace`

### ISSUE THREAD

**Issue by zenazn** [honeycombio/beeline-nodejs#423]
I think the `bindFunctionToTrace` function is defined here:
https://github.com/honeycombio/beeline-nodejs/blob/cf59603a7bb9b286b3e4e439a135c016cae2262c/lib/api/index.js#L206-L208

That seems to be a thin veneer over this function:
https://github.com/honeycombio/beeline-nodejs/blob/cf59603a7bb9b286b3e4e439a135c016cae2262c/lib/async_tracker.js#L37-L80

From reading the code, I'd describe `bindFunctionToTrace` as a function that returns the same type as its input (the argument is intended to be a function, but it seems to work for any value). I'd expect the type of such a function to be e.g., `bindFunctionToTrace<T>(fn: T): T`

But the declared typescript type of `bindFunctionToTrace` isn't that at all!
https://github.com/honeycombio/beeline-nodejs/blob/cf59603a7bb9b286b3e4e439a135c016cae2262c/lib/types.d.ts#L142

Without having done too much detective work here, it seems like someone may have copied the type of `runWithoutTrace` by accident?

Happy to submit a PR for this if helpful!

**Comment by JamieDanielson** [comment]
Thank you @zenazn! We will take a look and let you know if a PR is the next best step.

**Comment by zenazn** [comment]
@JamieDanielson I found myself working around this issue again in our codebase, and wanted to check in on this again. Anything I can do to help?

It looks like I'm not the only person who's reported this: https://github.com/honeycombio/beeline-nodejs/issues/412. I think @MikeGoldsmith's resolution to that ticket isn't quite right!

**Comment by JamieDanielson** [comment]
Hi @zenazn , thanks for re-raising this issue! We reviewed and it seems like the right change to make. We went ahead and created the PR with the change, and you'll see it come out in the next version release. 👍

**Comment by zenazn** [comment]
Thank you @JamieDanielson!
