### ISSUE TITLE
Switch npm publish to a team token

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/beeline-nodejs#439]
NPM publish currently uses my personal token

- [x] Get access to `honycombio` NPM organization
- [x] Create shared NPM account
- [x] Update CI to publish using shared account token

**Comment by MikeGoldsmith** [comment]
Tried to create npm org called 'honeycombio' and 'honeycomb', but both failed with "not available" errors. After searching for these profiles, both exist as organisations without any packages.

Hopefully we can take ownership of one of these to use.

**Comment by MikeGoldsmith** [comment]
Christine and a few others were already members of the honeycombio npm organization and I am now too.

**Comment by MikeGoldsmith** [comment]
Created shared account, waiting for it to be added to honeycomb org then will update CI access tokens.

**Comment by MikeGoldsmith** [comment]
Updated both libhoney-js & beeline-nodejs to use new shared account access token when publishing packages during CI releases.
