### ISSUE TITLE
Typescript for sampleHook and presendHook are a bit vague

### ISSUE THREAD

**Issue by glenjamin** [honeycombio/beeline-nodejs#507]
**Is your feature request related to a problem? Please describe.**

The current type definitions are as follows

https://github.com/honeycombio/beeline-nodejs/blob/2334c7fadfbb701c3e8f8b9a3a5a509fb648ea9d/lib/types.d.ts#L18-L19
```ts
    samplerHook?(event: unknown): SamplerResponse;
    presendHook?(event: unknown): void;
```

This requires a typescript consumer to either use type assertions or type checks before interacting with the `event` in their implementations.

**Describe the solution you'd like**

Technically both of these are of type `libhoney.Event`, and could be typed as such - although it might be cleaner to have a custom type in the beeline definition which hides the internals and only exposes the properites that an implementor should interact with, such as
```ts
interface Event {
  data: { [key: string]: unknown }
}
```

I'm happy to send in a PR for this, but I figured I'd report the issue first to get a steer on whether to use a narrower type or the libhoney Event

**Describe alternatives you've considered**

Currently in my definition of `presendHook` I can apply an inline type annotation to the function argument, and typescript will trust that I know what I'm doing and that's actually the type I'm getting.

**Additional context**

**Comment by MikeGoldsmith** [comment]
Hey @glenjamin - thanks for creating the issue.

Adding a type definition for the event makes sense. I don't mind exposing the libhoney.Event type here though as an extra layer doesn't really give us much other than stopping people doing silly things 😄 .

We'd be open to you putting those changes in a PR 👍🏻
