### ISSUE TITLE
sec: critical vulnerability in transitive dep vm2 (via libhoney)

### ISSUE THREAD

**Issue by bgowers** [honeycombio/beeline-nodejs#697]
**Versions**
Beeline: 4.0.0

**Description**
We have been notified of a new critical vulnerability in the [vm2](https://www.npmjs.com/package/vm2) (v3.9.19) package which is a nested dependancy of honeycomb-beeline. We have also found that vm2 is no longer being maintained.

Can vm2 be swapped out with some other maintained dependency?

![image](https://github.com/honeycombio/beeline-nodejs/assets/24320064/175ed7bf-a87d-4470-9e60-32c3643b08bc)

**Comment by bgowers** [comment]
I had a look through the dependencies and their most recent versions still leave a trail to vm2 (at no point does one dependency swap out for another that doesn't use vm2).

**Comment by bgowers** [comment]
Just found an open issue on degenerator's https://github.com/TooTallNate/proxy-agents/issues/218.

**Comment by robbkidd** [comment]
We're keeping an eye on upstream for a fix for the moment.

In the meantime, here's some information about Honeycomb's use of vm2:

* vm2 comes in to Beeline's dependencies through our libhoney library for telemetry event creation and transmission
    * libhoney -> superagent-proxy -> pac-proxy-agent-> (some more stuff) -> vm2
* [superagent-proxy is only loaded into the JS runtime environment by libhoney](https://github.com/honeycombio/libhoney-js/blob/v4.0.1/src/transmission.js#L337-L338) if you have configured libhoney or Beeline to send data to Honeycomb through an HTTP proxy, generally through setting [some conventional environment variables](https://www.npmjs.com/package/proxy-from-env#environment-variables)
* superagent-proxy only engages the code path that uses vm2 if you are supplying [proxy connection details with proxy auto-config (PAC) file](https://github.com/TooTallNate/proxy-agents/tree/main/packages/proxy-agent#proxy-agent) retrieved from a URL starting with `pac*`

**Comment by robbkidd** [comment]
We'll be tracking efforts to address this dependency vulnerability in [the libhoney-js repo](https://github.com/honeycombio/libhoney-js). While this issue is left open on the Beeline, in lieu of adding commentary here, I encourage you to provide contributions towards a solution over on matching [the libhoney-js issue](https://github.com/honeycombio/libhoney-js/issues/380).

**Comment by vreynolds** [comment]
Patched version of [libhoney released](https://github.com/honeycombio/libhoney-js/releases/tag/v4.1.0)! Beeline will accept any version 4.x.x of libhoney, so this can be resolved by upgrading your transitive dependency on libhoney to latest release.
