### ISSUE TITLE
send to different datasets

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#8]
honeycombio/honeycomb-rails sends to two datasets:  `dataset` and `db_dataset`.  for the nodejs stuff we likely need (at least 3):  `app`, `db`, and `services` where `services` is requests made to non-db external resources.

**Comment by toshok** [comment]
removing the `before-ga` label, adding `investigate further`.  This is the direction we're going in for the time being.

**Comment by vreynolds** [comment]
Housekeeping: closing, no longer relevant
