### ISSUE TITLE
Dirty working directory after npm install

### ISSUE THREAD

**Issue by garthk** [honeycombio/beeline-nodejs#84]
[`prettier` is pretty opinionated][so].

[So is `npm`][much].

We've set them up to fight each other forever.

`lint-staged` forces `prettier` to change `package.json` even if it's listed in `.prettierignore`, so all commits will have long `package-lock.json` lines wrapped and short `package.json` lists collapsed into a single line.

When we check out and `npm install`, `npm` reverses the change. And, so, _ad infinitum_.

[so]: https://github.com/npm/npm/issues/17973#issuecomment-318559060
[much]: https://prettier.io/docs/en/option-philosophy.html

**Comment by vreynolds** [comment]
Closing this issue as there has been no actively for a while. If you feel this should be re-visited, please reopen.
