### ISSUE TITLE
Trace concurrent actions

### ISSUE THREAD

**Issue by mgax** [honeycombio/beeline-nodejs#93]
Beeline assumes that, within a trace, all actions are sequential, and keeps an internal stack of spans to generate parent-child relationships. This assumption breaks down with e.g. concurrent database queries. Is it possible to trace those events and preserve the correct span containment?

**Comment by mgax** [comment]
My current solution is to flatten the span tree by monkeypatching beeline: https://gist.github.com/mgax/26fc2a4727f1f813f06368edb05d927a/edit

**Comment by toshok** [comment]
yep, was planning on working on this today.  nicely timed issue :)

**Comment by toshok** [comment]
The wrinkles with async spans mostly involve the `AsyncTracker` code.  Creating async spans needs to propagate something different than the existing trace-level context down to child async contexts.  One way to think about it (though I'm not sure this implementation would be all that great) would be to create a new trace-level context at each async span creation with the async span as the only span in the stack.

I think solutions that skip the stack will break down when there are normal child spans of those async spans.  Those should be synchronous within the context of the root async span.  That said, it seems likely that all spans (aside from those created using synchronous primitives like `withSpan`) throughout the beeline will be async so it really does come back to how to fix context propagation for async spans.

**Comment by toshok** [comment]
I'm using this as my current motivating example/test case:

```javascript
/* eslint-env node */
let beeline = require("honeycomb-beeline")();

// this doesn't currently work.  when it does, the trace should look like:
//
//    + - root
//    |
//    + - + - fast
//    |   |
//    |   + - fast-child
//    |
//    + - + - slow
//        |
//        + - slow-child

function slowSpan() {
  let asyncSpan = beeline.startSpan({ name: "slow" });
  return new Promise(resolve => {
    setTimeout(() => {
      beeline.withSpan({ name: "slow-child" }, () => {});
      beeline.finishSpan(asyncSpan);
      resolve();
    }, 5000);
  });
}

function fastSpan() {
  let asyncSpan = beeline.startSpan({ name: "fast" });
  return new Promise(resolve => {
    setTimeout(() => {
      beeline.withSpan({ name: "fast-child" }, () => {});
      beeline.finishSpan(asyncSpan);
      resolve();
    }, 1000);
  });
}

let rootSpan = beeline.startTrace({ name: "root" });

// the order of fast/slow is important here.  we want the fast span to be first
// on the context stack such that it'll finish before the slow one and we'll get
// the error.
Promise.all([fastSpan(), slowSpan()]).then(() => beeline.finishTrace(rootSpan));
```

it 100% of the time reproduces the error:

```
$ DEBUG=honeycomb-beeline:* node async-motivating-example.js 
  honeycomb-beeline:event using impl: libhoney-event +0ms
.writeKey must be a non-empty string
  honeycomb-beeline:event -------------------
  honeycomb-beeline:event     honeycomb-beeline error: finishing an event with unfinished nested events. almost certainly not what we want.
  honeycomb-beeline:event     please paste this message (everything between the "----" lines) into an issue
  honeycomb-beeline:event     at https://github.com/honeycombio/beeline-nodejs/issues.  feel free to edit
```

**Comment by toshok** [comment]
so the api in #94 fixes the above test case, and also (once I converted `lib/instrumentation/https.js` to use `createAsyncSpan`) fixes this test:

```
let beeline = require("honeycomb-beeline")();
  
const express = require("express"),
      https = require("https"),
      http = require("http"),
      process = require("process");

let externalSites = [
  "https://www.google.com",
  "https://airbnb.com",
  "https://ui.honeycomb.io",
  "https://www.honeycomb.io",
  "https://www.cnn.com",
  "https://www.msnbc.com",
];

let app = express()

app.get('/', (req, res) => {
  Promise.all(externalSites.map(s => doOutboundRequest(s)))
    .then(times => {
      res.send(`<table> ${externalSites.map((s,i) => `<tr><td>${s}</td><td>${times[i].toFixed(2)}</td>`)} </table>`);
    });
});

function doOutboundRequest(url) {
  return new Promise(resolve => {
    let startTimeHR = process.hrtime();
    https.get(url, (httpsRes) => {
      const duration = process.hrtime(startTimeHR);
      const durationMs = (duration[0] * 1e9 + duration[1]) / 1e6;
      resolve(durationMs);
    });
  });
}

app.listen(3000, () => console.log('Example app listening on port 3000!'));
```

**Comment by toshok** [comment]
before `createAsyncSpan` the debug output gave multiple error messages, and the traces as send to honeycomb were often broken:

![image](https://user-images.githubusercontent.com/24245/47526874-f0e29100-d855-11e8-83f2-7a8cee04218c.png)


after converting `https.js` to use `createAsyncSpan`:

![image](https://user-images.githubusercontent.com/24245/47526858-e45e3880-d855-11e8-8a7b-ddad67d04863.png)
